# frozen_string_literal: true

module Micro
  module Menu
    module Icons
      ICON_LIST = {
        'run' => "\ueb9e",
        'terminal' => "\uea85",
        'github' => "\uea84",
        'chart' => "\ue760",
        'jira' => "\ue75c",
        'settings' => "\ue615",
        'link' => "\ueb15",
        'ai' => '',
        'android' => '',
        'apple' => '',
        'audio' => '',
        'avro' => '',
        'c' => '',
        'clj' => '',
        'coffee' => '',
        'conf' => '',
        'cpp' => '',
        'css' => '',
        'd' => '',
        'dart' => '',
        'db' => '',
        'diff' => '',
        'doc' => '',
        'docker' => '',
        'ebook' => '',
        'env' => '',
        'epub' => '',
        'erl' => '',
        'file' => '',
        'font' => '',
        'gform' => '',
        'git' => '',
        'go' => '',
        'gruntfile' => '',
        'hs' => '',
        'html' => '',
        'image' => '',
        'iml' => '',
        'java' => '',
        'js' => '',
        'json' => '',
        'jsx' => '',
        'less' => '',
        'log' => '',
        'lua' => '',
        'md' => '',
        'mustache' => '',
        'npmignore' => '',
        'pdf' => '',
        'php' => '',
        'pl' => '',
        'ppt' => '',
        'psd' => '',
        'py' => '',
        'r' => '',
        'rb' => '',
        'rdb' => '',
        'react' => 'ﰆ',
        'rss' => '',
        'rubydoc' => '',
        'sass' => '',
        'scala' => '',
        'shell' => '',
        'sqlite3' => '',
        'styl' => '',
        'tex' => '',
        'ts' => '',
        'twig' => '',
        'txt' => '',
        'video' => '',
        'vim' => '',
        'vue' => '﵂',
        'windows' => '',
        'xls' => '',
        'xml' => '',
        'yarn' => '',
        'yml' => '',
        'zip' => ''
      }

      def self.all
        ICON_LIST
      end
    end
  end
end
