name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.1'
          - '3.1.0'
          - '3.0.0'
          - '2.7.0'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run Specs
      run: bundle exec rake

    - name: Create Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage/
